select * from yzorder where MEM_ID='scott' order by ORDER_DATE desc;

select * from yzorder;

insert into YZCUSTOMIZE (CTMZ_NO, CTMZ_MODEL, CTMZ_COLOR, CTMZ_PRICE, CTMZ_IMAGE1, CTMZ_IMAGE2) 
VALUES (1,'yzy350mr', 'mr', 1450,'yzy350mr1.png','yzy350mr5.png');

insert into YZCUSTOMIZE (CTMZ_NO, CTMZ_MODEL, CTMZ_COLOR, CTMZ_PRICE, CTMZ_IMAGE1, CTMZ_IMAGE2) 
VALUES (2,'yzy350tan', 'ta', 1300,'yzy350ta1.png','yzy350ta5.png');

insert into YZCUSTOMIZE (CTMZ_NO, CTMZ_MODEL, CTMZ_COLOR, CTMZ_PRICE, CTMZ_IMAGE1, CTMZ_IMAGE2) 
VALUES (3,'yzy350pb', 'pb', 1250,'yzy350pb1.png','yzy350pb5.png');

insert into YZCUSTOMIZE (CTMZ_NO, CTMZ_MODEL, CTMZ_COLOR, CTMZ_PRICE, CTMZ_IMAGE1, CTMZ_IMAGE2) 
VALUES (4,'yzy350tw', 'tw', 575,'yzy350tw1.png','yzy350tw5.png');

insert into YZCUSTOMIZE (CTMZ_NO, CTMZ_MODEL, CTMZ_COLOR, CTMZ_PRICE, CTMZ_IMAGE1, CTMZ_IMAGE2) 
VALUES (5,'yzy350td', 'td', 2295,'yzy350td1.png','yzy350td5.png');

SELECT * FROM YZCUSTOMIZE;

-- 아래 두 경로의 모든 이미지 파일을 반드시 제거후 실행해주세요.
-- C:\workspaces\jsp\kanye\WebContent\reviewupload
-- C:\workspaces\jsp\kanye\WebContent\reviewthumbnailupload


-- 외래키 -> 기본키 -> 테이블 순으로 제거
ALTER TABLE REVIEW DROP CONSTRAINT REVIEW_MEM_ID_FK;
ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_CTMZ_NO_FK;
ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_MEM_ID_FK;
ALTER TABLE YZORDER DROP CONSTRAINT YZORDER_ORDER_STATUS_FK;

ALTER TABLE MEMBER DROP PRIMARY KEY;
ALTER TABLE REVIEW DROP PRIMARY KEY;
ALTER TABLE CUSTOMIZE DROP PRIMARY KEY;
ALTER TABLE ORDERS DROP PRIMARY KEY;

DROP TABLE MEMBER PURGE;
DROP TABLE REVIEW PURGE;
DROP TABLE CUSTOMIZE PURGE;
DROP TABLE ORDERS PURGE;





-- 외래키 -> 기본키 -> 테이블 순으로 제거
ALTER TABLE YZREVIEW DROP CONSTRAINT YZREVIEW_MEM_ID_FK;
ALTER TABLE YZORDER DROP CONSTRAINT YZORDER_CTMZ_NO_FK;
ALTER TABLE YZORDER DROP CONSTRAINT YZORDER_MEM_ID_FK;

ALTER TABLE YZMEMBER DROP PRIMARY KEY;
ALTER TABLE YZREVIEW DROP PRIMARY KEY;
ALTER TABLE YZCUSTOMIZE DROP PRIMARY KEY;
ALTER TABLE YZORDER DROP PRIMARY KEY;
ALTER TABLE YZSTATUS DROP PRIMARY KEY;

DROP TABLE YZMEMBER PURGE;
DROP TABLE YZREVIEW PURGE;
DROP TABLE YZCUSTOMIZE PURGE;
DROP TABLE YZORDER PURGE;
DROP TABLE YZSTATUS PURGE;

SELECT * FROM TAB;




-- MEMBER 테이블 생성
CREATE TABLE YZMEMBER(
	MEM_ID			VARCHAR2(16)	CONSTRAINT YZMEMBER_ID_PK PRIMARY KEY,
	MEM_PASSWORD		VARCHAR2(30)	CONSTRAINT YZMEMBER_PASSWORD_NN NOT NULL,
	MEM_NAME			VARCHAR2(54),
	MEM_EMAIL		VARCHAR2(30)	CONSTRAINT YZMEMBER_EMAIL_NN NOT NULL,
	MEM_HOME			VARCHAR2(140),
	MEM_PHONE		VARCHAR2(12),
	MEM_GRADE		NUMBER(1)		CONSTRAINT YZMEMBER_GRADE_NN NOT NULL,
	MEM_DATE			DATE		CONSTRAINT YZMEMBER_DATE_NN NOT NULL
);


-- REVIEW 테이블 생성
CREATE TABLE YZREVIEW(
	REVIEW_NO		NUMBER(7)	CONSTRAINT YZREVIEW_NO_PK PRIMARY KEY,
	REVIEW_IMAGE		VARCHAR2(300)	CONSTRAINT YZREVIEW_IMAGE_NN NOT NULL,
	REVIEW_MESSAGE	VARCHAR2(600),
	REVIEW_DATE		DATE		CONSTRAINT YZREVIEW_DATE_NN NOT NULL,
	REVIEW_RATE		NUMBER(2)	CONSTRAINT YZREVIEW_RATE_NN NOT NULL,
	REVIEW_READCOUNT	NUMBER(7)	CONSTRAINT YZREVIEW_READCOUNT_NN NOT NULL,
	MEM_ID			VARCHAR2(16)	CONSTRAINT YZREVIEW_MEM_ID_NN NOT NULL 
);

ALTER TABLE YZREVIEW
ADD CONSTRAINT YZREVIEW_MEM_ID_FK
FOREIGN KEY(MEM_ID)
REFERENCES YZMEMBER(MEM_ID);


-- CUSTOMIZE 테이블 생성
CREATE TABLE YZCUSTOMIZE(
	CTMZ_NO			NUMBER(4)	CONSTRAINT YZCUSTOMIZE_NO_PK PRIMARY KEY,
	CTMZ_MODEL		VARCHAR2(50)	CONSTRAINT YZCUSTOMIZE_MODEL_NN NOT NULL,
	CTMZ_COLOR		VARCHAR2(15)	CONSTRAINT YZCUSTOMIZE_COLOR_NN NOT NULL,
--	CTMZ_SIZE		NUMBER(3)	CONSTRAINT YZCUSTOMIZE_SIZE_NN NOT NULL,
	CTMZ_PRICE		NUMBER(8)	CONSTRAINT YZCUSTOMIZE_PRICE_NN NOT NULL,
--	CTMZ_INVENTORY		NUMBER(3)	CONSTRAINT YZCUSTOMIZE_INVENTORY_NN NOT NULL,
	CTMZ_IMAGE1		VARCHAR2(300)	CONSTRAINT YZCUSTOMIZE_IMAGE1_NN NOT NULL,
	CTMZ_IMAGE2		VARCHAR2(300)	CONSTRAINT YZCUSTOMIZE_IMAGE2_NN NOT NULL
);


-- STATUS 테이블 생성 (0, 1, 2 만 들어가며 각각 배송전, 배송중, 배송완료를 의미)
CREATE TABLE YZSTATUS(
	ORDER_STATUS	NUMBER(1)	CONSTRAINT YZSTATUS_ORDER_STATUS_PK PRIMARY KEY
);

select * from YZSTATUS;

-- 0 / 1 / 2 순서대로 배송전 배송중 배송완료
INSERT INTO YZSTATUS VALUES(0);
INSERT INTO YZSTATUS VALUES(1);
INSERT INTO YZSTATUS VALUES(2);


-- ORDER 테이블 생성
CREATE TABLE YZORDER
(
	ORDER_NO		NUMBER(8)	CONSTRAINT YZORDER_NO PRIMARY KEY,
	CTMZ_NO			NUMBER(4)	CONSTRAINT YZORDER_CTMZ_NO_NN NOT NULL,
	MEM_ID			VARCHAR2(16)	CONSTRAINT YZORDER_MEM_ID_NN NOT NULL,
	ORDER_STATUS		NUMBER(1)	CONSTRAINT YZORDER_ORDER_STATUS_NN NOT NULL,
	ORDER_PHONE		NUMBER(12)	CONSTRAINT YZORDER_PHONE_NN NOT NULL,
	ORDER_ADDRESS		VARCHAR2(140)	CONSTRAINT YZORDER_ADDRESS_NN NOT NULL,
	ORDER_NAME		VARCHAR2(54)	CONSTRAINT YZORDER_NAME_NN NOT NULL,
	ORDER_MESSAGE		VARCHAR2(150),
	ORDER_DATE		DATE		CONSTRAINT YZORDER_DATE_NN NOT NULL,
	ORDER_SIZE		NUMBER(3)	CONSTRAINT YZORDER_SIZE_NN NOT NULL
);

ALTER TABLE YZORDER
ADD CONSTRAINT YZORDER_CTMZ_NO_FK
FOREIGN KEY (CTMZ_NO)
REFERENCES YZCUSTOMIZE(CTMZ_NO);

ALTER TABLE YZORDER
ADD CONSTRAINT YZORDER_MEM_ID_FK
FOREIGN KEY (MEM_ID)
REFERENCES YZMEMBER(MEM_ID);

ALTER TABLE YZORDER
ADD CONSTRAINT YZORDER_ORDER_STATUS_FK
FOREIGN KEY (ORDER_STATUS)
REFERENCES YZSTATUS(ORDER_STATUS);


-- 잘 생성되었는지 확인
SELECT * FROM YZMEMBER;
SELECT * FROM YZREVIEW;
SELECT * FROM YZORDER;
SELECT * FROM YZCUSTOMIZE;




-- 이상, 기본적인 테이블 작업 끝.
--------------------------------------------------------------------



-- 쇼핑몰의 일반회원인 scott 계정 생성.
INSERT INTO YZMEMBER(
	MEM_ID,
	MEM_PASSWORD,
	MEM_NAME,
	MEM_EMAIL,
	MEM_HOME,
	MEM_PHONE,
	MEM_GRADE,
	MEM_DATE
)VALUES(
	'scott', 'tiger', '스캇', 'avc@abc.com', '서울', '01012345678', '0', sysdate
);

-- 쇼핑몰의 관리자인 admin 계정 생성.
INSERT INTO YZMEMBER(
	MEM_ID,
	MEM_PASSWORD,
	MEM_NAME,
	MEM_EMAIL,
	MEM_HOME,
	MEM_PHONE,
	MEM_GRADE,
	MEM_DATE
)VALUES(
	'admin', 'admin', '어드민', 'xyz@xyz.com', '서귀포시', '01056781234', '1', sysdate
);

INSERT INTO YZMEMBER(
	MEM_ID,
	MEM_PASSWORD,
	MEM_NAME,
	MEM_EMAIL,
	MEM_HOME,
	MEM_PHONE,
	MEM_GRADE,
	MEM_DATE
)VALUES(
	'oh', 'oh', '오현', 'avc@abc.com', '서울', '01012345678', '0', sysdate
);

SELECT * FROM YZMEMBER;





-------------------------------------------------
-- 이 아래는 실행할 필요 없음. 개인 작업 공간
-------------------------------------------------



select * from YZREVIEW;
TRUNCATE TABLE YZREVIEW;
SELECT MAX(REVIEW_NO) FROM YZREVIEW;


-- 최신순 으로 불러오기. 483 482 481 480 479 ...
-- 어째선지 ROWNUM에 RNUM같은 별도의 애칭을 안붙이면 동작을 안한다. 왜일까? 누구한테 물어보지?
SELECT * FROM (
		SELECT
		ROWNUM RNUM,
		REVIEW_NO,
		REVIEW_IMAGE,
		REVIEW_MESSAGE,
		REVIEW_DATE,
		REVIEW_RATE,
		REVIEW_READCOUNT
	FROM YZREVIEW ORDER BY REVIEW_NO DESC
)WHERE RNUM >= 21 AND RNUM <= 41;




SELECT * FROM YZREVIEW WHERE REVIEW_NO = 16;

SELECT * FROM YZMEMBER WHERE MEM_ID = 'scott' and MEM_PASSWORD = 'tiger';








